Pull toastr from npm instead of bower
knownasilya/ember-toastr pull request #16
Opened 2017-05-04 14:18 UTC by GramozKrasniqi

Other changes:
Travis build file changed to test for node 4 and 6.
Remove testing for older nodes beacuse of ES6 language support.

Tests passing locally, travis is green also.

2017-05-04 14:27 UTC, knownasilya requested changes
Thanks for this! Just a few comments, but everything else looks good.

2017-05-04 14:27 UTC, knownasilya commented on index.js
> +          production: vendor + '/toastr/build/toastr.min.js'
This shouldn't be necessary since ember-cli does a production build itself.

2017-05-04 14:27 UTC, knownasilya commented on index.js
> +          production: vendor + '/toastr/build/toastr.min.css'
Same as above

2017-05-04 14:27 UTC, knownasilya commented on package.json
> +    "toastr": "^2.1.2"
If this gets added to the user's project, it shouldn't be here (only in dev deps for dummy app).

2017-05-04 14:43 UTC, GramozKrasniqi commented on package.json
> +    "toastr": "^2.1.2"
Great thanks for the comments will do the changes :D

2017-05-04 14:56 UTC, knownasilya commented on package.json
> +    "toastr": "^2.1.2"
Just for toastr, not for ember-cli-babel. That needs to stay for transpilation of the addon.

2017-05-04 15:19 UTC, merged

2017-05-04 16:19 UTC, roberkules commented
i just tried to install `ember-toastr` and I noticed that it's still showing the `Install toastr.js from bower` blueprint. I guess it's because you didn't bump the package version (to `1.5.1` or `1.6`)?!

2017-05-04 16:41 UTC, knownasilya commented
I just merged this and haven't published the changes yet. Will try to get to it later today.

2017-05-04 18:47 UTC, roberkules commented
alright, sorry for being impatient ;)

2017-05-08 11:27 UTC, GramozKrasniqi commented
@knownasilya is there any way you could publish to npm please

2017-05-08 13:39 UTC, knownasilya commented
All set @GramozKrasniqi